### PR TITLE
367 add links to advanced search

### PR DESCRIPTION
**Pull request by BibianaC**
I have added links to the examples in `Advanced search` documentation.

Some of the links don't work, it adds extra quotes. Lines: 239, 258, 288, 296 and 297.

### CODE REVIEW

**Comment by robredpath** [comment]
This looks good, @BibianaC . I'm not sure about the orange underline though - it works on the orange link text elsewhere but it looks a bit weird under red example text. Can we make it red?

**Comment by robredpath** [comment]
(I've tested all the links btw and they all work as expected :) )

**Comment by BibianaC** [comment]
Thanks @robredpath . I will check the underline.

**Comment by BibianaC** [comment]
@robredpath the underline is fixed.

**Comment by robredpath** [comment]
Nice, thanks @BibianaC . @morchickit , what do you think?

**Comment by BibianaC** [comment]
@morchickit gentle reminder that we are waiting for your feedback.

**Comment by morchickit** [comment]
Sorry, missed this in my inbox. Checking

**Comment by morchickit** [comment]
My only concern is fuzzy search, because at the moment it doesn't work properly

**Comment by morchickit** [comment]
Other than the fuzzy, that has nothing to do with this code, we need to just document it well, looks ok!

**Pull request merged**
