### PR TITLE
[#213] [#246] An idea/option for explaining about GrantNav

### PR DESCRIPTION
**Pull request by caprenter**
Just adds some quotes to the front page. We can decide waht we want
them to say.

### CODE REVIEW

**Comment by robredpath** [comment]
I've emailed Katherine at 360 to see what she thinks, as she's been thinking about contextless visits a lot. 

In principle, I like the idea of having something on the front page that people can instantly relate to and say 'yes, this is for me'. However, quotes like this are often used for reviews (so do they come across as too marketing-ey?) and it's a big design change.

**Comment by caprenter** [comment]
This is probably really issue #246. I'll add that to the title of this issue.

**Comment by caprenter** [comment]
Fine by me

**Comment by robredpath** [comment]
As per our conversation earlier, I'm closing this for now. We might want to revive it in the future (potentially quite near future), depending on how the contextless visits conversation goes.

**Pull request closed without merging**
