### PR TITLE
Add grant programme details to CSV export

### PR DESCRIPTION
**Pull request by drkane**
See issue #370

### CODE REVIEW

**Comment by caprenter** [comment]
Thanks for this request @drkane 

On first glance this looks good. 

We tend to deploy any bug fixes and improvements on a monthly cycle in line with the data load deployment detailed over at http://grantnav.threesixtygiving.org/datasets/

I *think* we should be able to include this in the February deploy which will happen in the next week or so (although others will make that judgement, not me!)

In the meantime, I've put a [pull request in to accept our Contributor Agreement guidelines](https://github.com/OpenDataServices/grantnav/pull/372) that are missing from this repo. We should have had this in place before you made your request. Apologies for that. Before we can accept this contribution, in order to keep all contributions well licensed for the future, can I ask you to complete our contributor agreement?

We have a [generic agreement](http://contributoragreements.org/u2s/bm1v4q5je) that covers all code projects in the [Open Data Services GitHub Organisation](https://github.com/opendataservices)

Get in touch if any problems, or concerns.

Thanks again though for taking the time to create this pull request.

**Comment by drkane** [comment]
Great - thanks very much. As I say I'm new to this so the guidance is very helpful. I've submitted the contributor agreement (I think!)

Do you want me to rename the branch into the format from `contributing.md`?

**Comment by caprenter** [comment]
Thanks - yep. I've got a copy of the agreement, and I'm just trying to remember how to sign it and send it back!

No need to rename the branch. That guidance is useful, but this is easy enough to track as it is.

You should get direct email soon with our signed copy of the agreement.

**Comment by drkane** [comment]
Fantastic - thanks very much!

**Comment by Bjwebb** [comment]
This is now live on http://grantnav.threesixtygiving.org/

**Pull request merged**
