### PR TITLE
DC's final sprint tasks

### PR DESCRIPTION
**Pull request by caprenter**
A number of minor tickets in one request

Each ticket has it's own commit.

### CODE REVIEW

**Comment by robredpath** [comment]
Can we move the logo all the way over to the right? IMO it feels a bit weird where it is...

Otherwise, looks great!

**Comment by robredpath** [comment]
@caprenter ^^

**Comment by caprenter** [comment]
What does "Can we move the logo all the way over to the right?" mean? The text is where the Logo was.

**Comment by robredpath** [comment]
Sorry, I mean left. The text isn't where the logo was in my browser, there's just a hole where the logo used to be:

screen shot 2016-09-01 at 18 04 15

**Comment by robredpath** [comment]
@caprenter ^^

**Pull request merged**
