### PR TITLE
Include geo codes in data added by grantnav

### PR DESCRIPTION
**Pull request by edugomez**
#382 

This PR also gets rid of _(B)_ s in district names as for #345

### CODE REVIEW

**Comment by robredpath** [comment]
@edugomez am I right in thinking that a geocode added by GN will be indistinguishable from one provided by the publisher?

**Comment by edugomez** [comment]
@robredpath Yes

**Comment by robredpath** [comment]
@morchickit @KDuerden can I just check that this ^^ you're ok with? It does mean that a user doesn't know if the geocode data has been added by GN, which might weaken the case for it being supplied by the publisher (but does also make the data more useful, and thus potentially more used....)

**Comment by edugomez** [comment]
>  It does mean that a user doesn't know if the geocode data has been added by GN

The code in this PR only adds the geocodes supplemented by GN to the CSV/JSON downloads. We could do the following:
  
gn_geoc

In which case it is clear that the geographical data was added by GN (as the grant only includes post code). However, when the grant includes geo codes, users may get the impression that GN is duplicating data rather than enriching it.

Alternatively, it should also be possible to check whether the grant includes geo codes so as not show them under additional data in those cases.

**Comment by robredpath** [comment]
Great, thanks @KDuerden

**Comment by edugomez** [comment]
I have updated the code in this PR and now displays the section _Additional data added by Grantnav_ as in the screenshot above.

**Pull request merged**
