### PR TITLE
[#318] Add UTF-8 bom to CSV output

### PR DESCRIPTION
**Pull request by Bjwebb**
This helps spreadsheet programs realise that it's UTF-8.

### CODE REVIEW

**Comment by Bjwebb** [comment]
Would be useful for someone to check this with a copy of MS Excel.

**Comment by robredpath** [comment]
screen shot 2016-09-05 at 10 54 33

**Comment by robredpath** [comment]
@Bjwebb is ^^ correct?

**Comment by Bjwebb** [comment]
Looks good. Could you double check that it looks mangled when downloaded from the live site?

**Comment by robredpath** [comment]
screen shot 2016-09-05 at 11 32 41

**Pull request merged**
