### PR TITLE
[#340] Text edits

### PR DESCRIPTION
**Pull request by caprenter**
Final proof reading edits

### CODE REVIEW

**Comment by caprenter** [comment]
@Bjwebb any chance to merge and deploy this - or can someone else do it for you?

I guess if the site is live, these really need to be fixed asap.

**Comment by Bjwebb** [comment]
All deploys are password protected atm.

**Comment by Bjwebb** [comment]
Should the footer text be capitalised like this? It's inconsistent with the headings on the individual pages, which are more lower case, which I thought was preferred.

**Comment by caprenter** [comment]
See the instructions from Rachel in the ticket https://github.com/OpenDataServices/grantnav/issues/340
The text she supplied is different from how it was.

**Comment by caprenter** [comment]
We've had confirmation that this change is good to go from Rachel

**Pull request merged**
