### PR TITLE
[#216] Replace green/red icons with up down arrows in data tables

### PR DESCRIPTION
**Pull request by caprenter**
Uses CSS to change the icons used in the data tables on e.g. a funders page

Re-orders where 'extra-style' is loaded in the base template so that our
main.css file gets loaded last. This may have unintended consequences, please review.

### CODE REVIEW

**Comment by robredpath** [comment]
I feel like the arrows should point right when closed, and down when open. See http://ux.stackexchange.com/questions/5735/which-way-should-arrows-point-in-a-collapsible-accordion-left-down-down-up for some discussion of this. 

Thoughts?

**Comment by caprenter** [comment]
No thoughts for me. If you want to use a horizontal arrow the css would be \25b6 
(from https://brajeshwar.github.io/entities/ )

**Comment by robredpath** [comment]
Does anyone else have an opinion on this? @Bjwebb @kindly ?

**Comment by Bjwebb** [comment]
> I feel like the arrows should point right when closed, and down when open.

Yep, I'd agree with that.

**Comment by caprenter** [comment]
I'll change this...

**Pull request merged**
